name: Generate OSlib Package

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: waylon-cn/mcp-coroot/mcp-coroot

jobs:
  build:
    runs-on: ubuntu-latest
    
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }} 
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1      

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./
        file: ./Dockerfile
        push: true
        pull: true
        platforms: linux/amd64
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:v1.0
        provenance: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
    